SYMBOL_LIST = [
    "BTCUSDT", "LUNAUSDT", "ETHUSDT", "BNBUSDT", "SOLUSDT",
    "DOGEUSDT", "ETHBTC", "BNBBTC", "DOGEBTC", "SOLBTC",
    "SHIBUSDT", "TRXBTC", "XRPUSDT"
]

CRAWL_INTERVAL = 5  # 5 secs
