const SYMBOL_MAPPING = {
    "BTCUSDT": "BTC/USDT",
    "LUNAUSDT": "LUNA/USDT",
    "ETHUSDT": "ETH/USDT",
    "BNBUSDT": "BNB/USDT",
    "XRPUSDT": "XRP/USDT",
    "DOGEUSDT": "DOGE/USDT",
    "ETHBTC": "ETH/BTC",
    "BNBBTC": "BNB/BTC",
    "DOGEBTC": "DOGE/BTC",
    "SOLBTC": "SOL/BTC",
    "SHIBUSDT": "SHIB/USDT",
    "TRXBTC": "TRX/BTC",
    "SOLUSDT": "SOL/USDT",
}

export default SYMBOL_MAPPING