SYMBOL_LIST = [
    "BTCUSDT", "LUNAUSDT", "ETHUSDT", "BNBUSDT", "SOLUSDT",
    "DOGEUSDT", "ETHBTC", "BNBBTC", "DOGEBTC", "SOLBTC",
    "SHIBUSDT", "TRXBTC", "XRPUSDT"
]

MAX_PULL_TWEETS = 100
CRAWL_INTERVAL = 10  # 10 secs
