CMC_POSTS_COLLECTION = "cmc.posts"
CMC_STREAM_POSTS_COLLECTION = "cmc.stream.posts"
CMC_NEWS_COLLECTION = "cmc.news"
CMC_STREAM_NEWS_COLLECTION = "cmc.stream.news"
CMC_POSTS_ASSOC_COLLECTION = "cmc.posts_assoc"
CMC_STREAM_POSTS_ASSOC_COLLECTION = "cmc.stream.posts_assoc"
